apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube-chart.fullname" . }}
  labels:
    app: {{ include "sonarqube-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sonarqube-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sonarqube-chart.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.create | ternary (include "sonarqube-chart.serviceAccountName" .) "default" }}
      containers:
        - name: sonarqube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000
              name: http
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          env:
            - name: SONAR_JDBC_URL
              value: >-
                jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
            - name: SONAR_JDBC_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret | default (printf "%s-postgresql" .Release.Name) }}
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}

